### ISSUE TITLE
Collection page

### ISSUE THREAD

**Issue by ninabreznik** [ethereum-play/smartcontract.codes#10]
## `@todo`
- [x] Fix broken SVGs. They still don't show when we push to Github (in production) (@fionataeyang)
- [x] replace the logo (@fionataeyang)
  - @serapath is preparing a new logo so we'll replace that one 
- [x] fix css grid to use new specification (see codepen examples)
  - https://www.chromestatus.com/feature/6708326821789696
- [x] check if all elements are visible/behave how we want on Firefox and Safari too
  - I noticed search bar behaving weird in Firefox
- [ ] **LATER:** use random generator for creating profile images (default one and then based on their Metamask address) (@fionataeyang) (@ninabreznik)

---

**Comment by fionataeyang** [comment]
index.html needs to add a meta tag for the smart phone and table device to adapt the page.
<meta name="viewport" content="width=device-with, initial-scale=1"

**Comment by fionataeyang** [comment]
It needs a fixed height to extend a block for percentage, otherwise, it won't be worked. And also it caused a overflow with contents.

**Comment by ninabreznik** [comment]
@fionataeyang Can you please check if everything here is finished, if yes, we can close the issue :)

If not, let me know what?

Thanks!

**Comment by fionataeyang** [comment]
We haven't add the generator for creating profile images, but below 2 lists are done.
1. fix css grid
2. all elements are visible/behave are same.

Search input is an issue with multiple line when click enter, it's shown the cards.

**Comment by serapath** [comment]
close and transitioned to https://github.com/playproject-io/smartcontract.codes/issues/6
