### ISSUE TITLE
SEARCH BAR component

### ISSUE THREAD

**Issue by ninabreznik** [ethereum-play/smartcontract.codes#9]
## @TODO

- [ ] Show options on the search bar (see Google):
  - [ ] search code (contract DAO (...)
  - [ ] search by addresses (0x323094803)
  - [ ] search by keywords (deployed contract, open Zeppelin)
  - [ ] search only audited
  - [ ] search only curated (open Zeppelin i.e.)
  - [ ] search only solidity version 0.4.0 and newer

- [ ] show search params in the url

## LATER

- [ ] add features (autocomplete, suggest additional keywords (like Pinterest, Google image search), add filtering options etc.) (@ninabreznik)

- [ ] adapt syntax highlight to our theme (use code mirror, not highlight.js)
 (@fionataeyang )

**Comment by ninabreznik** [comment]
Inspiration

- [IBM SEARCH](https://www.ibm.com/search?lang=en&cc=us) - see also search tip
- [Skyscanner search](https://www.skyscanner.com.tw/transport/flights/tpet/tyoa/190819/190826/?adults=1&children=0&adultsv2=1&childrenv2=&infants=0&cabinclass=economy&rtn=1&preferdirects=false&outboundaltsenabled=false&inboundaltsenabled=false&ref=home#results) - search progress bar
- [Behance dropdowns of options](https://www.behance.net/search/?content=projects) - filters 
- [NerdyData search](https://nerdydata.com/reports/new?search=%7B%22all%22%3A%5B%7B%22type%22%3A%22code%22,%22value%22%3A%22function%20calculate%28%29%20%7B%22,%22name%22%3A%22function%20calculate%28%29%20%7B%22%7D%5D,%22any%22%3A%5B%5D,%22none%22%3A%5B%5D%7D) - code results

**Comment by serapath** [comment]
closing this issue and transitioning content to https://github.com/playproject-io/smartcontract.codes/issues/9
